version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      #- run:
      #    name: Install Docker
      #    command: |
      #      sudo apt-get update
      #      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - run:
          name: Build Docker image
          command: |
            ls
            docker build -t nodeapp:latest .
      - run:
          name: Test Docker image
          command: |
            docker run -d --name nodeappcontainer -p 8080:80 nodeapp
            sleep 5 # Donne un peu de temps au conteneur pour démarrer
            curl --retry 10 --retry-delay 5 -v http://localhost:8080/
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag nodetest:latest $DOCKERHUB_USERNAME/nodetest:latest
            docker push $DOCKERHUB_USERNAME/nodetest:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push